format_version: 1
frames:
  base_frame: base_link
  imu_frame: imu_link
  mag_frame: mag_link
flags:
  anchored: true
  mag_reference_invalid: false
  mag_disturbance_detected: false
  mag_dir_prior_from_driver_cov: true
mounts:
  R_BI:
    quaternion_wxyz:
    - 1.0
    - -8.952505963249463e-09
    - 4.647213230258481e-09
    - 1.8650833155045513e-25
    rot_cov_rad2:
    - - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
  R_BM:
    quaternion_wxyz:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    rot_cov_rad2:
    - - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
nuisance:
  imu:
    accel_bias_mps2:
    - 0.565750041676991
    - -0.06872021552768869
    - -2.436465099919608
    accel_A_row_major:
    - 1.0006108593518037
    - 0.007915145167533423
    - -0.004937724894699125
    - -0.00567880439917069
    - 0.9946487419137248
    - -0.06066676302127705
    - -0.014562896721060889
    - -0.03509954562277217
    - 0.9482004891028823
    accel_param_cov_row_major_12x12:
    - 1115517.2409428903
    - -552131.8870028513
    - 81143.37966428226
    - 2947874.178187448
    - -854955.8563096619
    - -1714245.8116333752
    - 733641.3898341358
    - -716121.522007117
    - -593066.3456889442
    - -1178282.0236699714
    - -223698.09484569146
    - 666415.2323506409
    - -552131.8870028513
    - 2730853.7709139576
    - -740806.2880063007
    - -9315729.156064738
    - 3406018.628851164
    - 5858454.001632072
    - -3054338.7426513834
    - 1723198.2256166963
    - 2342823.781561451
    - 3173731.9958107397
    - 156228.6167305606
    - -1923335.407530344
    - 81143.37966428226
    - -740806.2880063007
    - 1220271.1480915113
    - 2286362.9409362483
    - -1180556.4758519118
    - -1492885.0630827353
    - 616689.3607365779
    - -1174579.2626073265
    - -617589.5451932742
    - -1878701.147370634
    - -339368.1097239264
    - 1186039.184833298
    - 2947874.178187448
    - -9315729.156064738
    - 2286362.9409362483
    - 55860608.483130835
    - -16703581.241783585
    - -34643846.70122786
    - 14628380.544352956
    - -10685275.671186747
    - -11121994.734770045
    - -18423782.59599131
    - -1566502.0135522187
    - 10827753.147440586
    - -854955.8563096619
    - 3406018.628851164
    - -1180556.4758519118
    - -16703581.241783585
    - 6082909.066375506
    - 10515199.453175966
    - -7214862.888123127
    - 2631341.9594215406
    - 4981063.990867504
    - 4820076.654032119
    - 1707666.3855457276
    - -2718659.2775429715
    - -1714245.8116333752
    - 5858454.001632072
    - -1492885.0630827353
    - -34643846.70122786
    - 10515199.453175966
    - 21520547.054167263
    - -9474092.854417061
    - 6530945.073354503
    - 7128760.2282973565
    - 11306929.203365479
    - 1128495.5665275436
    - -6632292.769264577
    - 733641.3898341358
    - -3054338.7426513834
    - 616689.3607365779
    - 14628380.544352956
    - -7214862.888123127
    - -9474092.854417061
    - -127094.74804595773
    - -7203359.745804626
    - -1285686.6137863656
    - -11699402.494024599
    - 953457.0384442783
    - 7047390.620384754
    - -716121.522007117
    - 1723198.2256166963
    - -1174579.2626073265
    - -10685275.671186747
    - 2631341.9594215406
    - 6530945.073354503
    - -7203359.745804626
    - -799.3391595433868
    - 4414288.283272206
    - -773671.9898870133
    - 962798.6553064367
    - 452911.9817050358
    - -593066.3456889442
    - 2342823.781561451
    - -617589.5451932742
    - -11121994.734770045
    - 4981063.990867504
    - 7128760.2282973565
    - -1285686.6137863656
    - 4414288.283272206
    - 1640188.781002507
    - 7104246.432929326
    - -402248.1781538679
    - -4282903.578884045
    - -1178282.0236699714
    - 3173731.9958107397
    - -1878701.147370634
    - -18423782.59599131
    - 4820076.654032119
    - 11306929.203365479
    - -11699402.494024599
    - -773671.9898870133
    - 7104246.432929326
    - 773871.8246769004
    - 1775331.1044286317
    - -419552.46860638633
    - -223698.09484569146
    - 156228.6167305606
    - -339368.1097239264
    - -1566502.0135522187
    - 1707666.3855457276
    - 1128495.5665275436
    - 953457.0384442783
    - 962798.6553064367
    - -402248.1781538679
    - 1775331.1044286317
    - -240687.1741509616
    - -1108158.2591431031
    - 666415.2323506409
    - -1923335.407530344
    - 1186039.184833298
    - 10827753.147440586
    - -2718659.2775429715
    - -6632292.769264577
    - 7047390.620384754
    - 452911.9817050358
    - -4282903.578884045
    - -419552.46860638633
    - -1108158.2591431031
    - 226120.05443875512
    gyro_bias_rads:
    - -0.035899288401296435
    - -0.01008377625010952
    - -0.041914287058259295
    gyro_bias_cov_row_major_3x3:
    - 2.714024196951977e-08
    - -4.9965151202550634e-09
    - 1.1524732412460775e-09
    - -4.9965151202550634e-09
    - 3.713253623292377e-08
    - 2.095360274758992e-09
    - 1.1524732412460775e-09
    - 2.095360274758992e-09
    - 2.4934669123112492e-08
  mag:
    offset_t:
    - 0.0
    - 0.0
    - 0.0
    offset_cov_row_major_3x3:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    R_m_unitless2_row_major_3x3:
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.001
    R_m0_unitless2_row_major_3x3:
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.001
quality:
  raw_samples: 1607
  steady_segments: 1
  keyframes: 1
  total_duration_sec: 0.0
  accel_residual_rms: 0.020463050417404635
  mag_residual_rms: 0.020463050417404635
  diversity:
    gravity_max_angle_deg: 0.0
    mag_proj_max_angle_deg: 0.0
