timestamp_s: 1767566872.3240376
bandwidth_mode: 1
raw_rate_hz: 100
covariance_t2:
  - 3.9134297058482789e-15
  - -1.3678574977841957e-16
  - -1.6741827751436068e-16
  - -1.3678574977841957e-16
  - 4.0531283200375087e-15
  - 2.7555056863820905e-16
  - -1.6741827751436068e-16
  - 2.7555056863820905e-16
  - 4.4375366140700242e-15
offset_t:
  - -9.460449218750001e-07
  - -2.0874023437500002e-05
  - -9.545898437499999e-06