version: 1
frame_id: imu_link
created_unix_ns: 1767425482597001250
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 27.539057274787051
  stddev_c: 1.9838387037595999
raw_noise:
  accel_bias_mps2:
    - 1.9818666342155571
    - 0.37823509153012841
    - -0.71770155541238567
  gyro_bias_rads:
    - -0.0082827312800692124
    - 0.039024705118094992
    - -0.040911572002860982
  accel_stddev_mps2:
    - 0.14476455202651412
    - 0.12502064893044632
    - 0.14717846100911181
  gyro_stddev_rads:
    - 0.088162396458017628
    - 0.055165499631265269
    - 0.051000010830978965
  accel_cov_mps2_2:
    -
      - 0.020956775523437315
      - -0.00085672545315875924
      - -0.00026327911474877401
    -
      - -0.00085672545315875913
      - 0.015630162658989907
      - -0.0035109945466804036
    -
      - -0.0002632791147487739
      - -0.0035109945466804031
      - 0.021661499385010642
  gyro_cov_rads2_2:
    -
      - 0.0077726081492206795
      - 0.00062628393883717363
      - 0.0013841298810166123
    -
      - 0.00062628393883717363
      - 0.0030432323495671282
      - -0.00032902846799993631
    -
      - 0.0013841298810166121
      - -0.00032902846799993609
      - 0.0026010011047599715
  stationary_samples: 1620
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.044860133299153476
    - 0.03417447732849465
    - 0.023353902416970471
  accel_bias_stddev_mps2:
    - 4.410567492764816
    - 4.4325871430267227
    - 7.3645318767804779
accel_calibration:
  bias_mps2:
    - -0.012319415931480761
    - -0.66353028717139684
    - -2.2564037192065891
  A:
    -
      - 1.0030565833181433
      - 0
      - 0
    -
      - -0.031637003335407789
      - 1.0277995487752376
      - 0
    -
      - -0.0050504241497783499
      - -0.004594762935392553
      - 0.96224477130760877
  bias_stddev_mps2:
    - 0.097200837308727236
    - 0.08426660468430959
    - 0.083308685968909543
  A_stddev:
    -
      - 0.010791976714772233
      - 0
      - 0
    -
      - 0.062130638935412749
      - 0.012221752433222053
      - 0
    -
      - 0.024049802523885357
      - 0.016693317438403771
      - 0.0090223441977237712
ellipsoid:
  W:
    -
      - 1.0071489161020046
      - -0.032493292251041396
      - -0.0048597442310098927
    -
      - -0.032493292251041396
      - 1.0563930243090145
      - -0.0044212866099794844
    -
      - -0.0048597442310098927
      - -0.0044212866099794844
      - 0.9259149999088323
  center:
    - -0.012319415931480761
    - -0.66353028717139684
    - -2.2564037192065891
fit_quality:
  rms_residual_mps2: 0.10508537345129423
  num_clusters: 15
  num_samples: 2051
noise_fit:
  stationary_samples: 1620
  method: bootstrap_rest
  phase: bootstrap