version: 1
frame_id: imu_link
created_unix_ns: 1767165164412925210
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 27.794782689302753
  stddev_c: 1.3181979602549538
noise:
  accel_stddev_mps2:
    - 0.038872326923518344
    - 0.04540255755902893
    - 0.050148229212713738
  gyro_stddev_rads:
    - 0.0049977210402572057
    - 0.0053099582828421256
    - 0.003397747677253348
accel_calibration:
  bias_mps2:
    - 0.099154423204777312
    - -0.47676409430684624
    - -2.1719357080225725
  A:
    -
      - 1.0052638885089427
      - 0
      - 0
    -
      - 0.009710047391773809
      - 1.0065131910457445
      - 0
    -
      - 0.0053869944749101641
      - 0.00031106998115057596
      - 0.9672921979481961
  bias_stddev_mps2:
    - 0.042543600952376456
    - 0.048990048333473792
    - 0.047833697017089304
  A_stddev:
    -
      - 0.0049341769839340794
      - 0
      - 0
    -
      - 0.012954667341881063
      - 0.0061489761450054178
      - 0
    -
      - 0.01208235575396226
      - 0.013123050816510223
      - 0.0052514563472121582
ellipsoid:
  W:
    -
      - 1.0106787902699432
      - 0.0097749665177694345
      - 0.0052107977259706409
    -
      - 0.0097749665177694345
      - 1.0130689005136206
      - 0.00030089556578284454
    -
      - 0.0052107977259706409
      - 0.00030089556578284454
      - 0.93565419621145218
  center:
    - 0.099154423204777312
    - -0.47676409430684624
    - -2.1719357080225725
fit_quality:
  rms_residual_mps2: 0.082583491443266363
  num_clusters: 22
  num_samples: 8884