version: 1
frame_id: imu_link
created_unix_ns: 1767437050093379473
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 28.52007887484557
  stddev_c: 1.9344056495031046
raw_noise:
  accel_bias_mps2:
    - 0.44721681223002085
    - -4.302875882906708
    - 4.5610748437130235
  gyro_bias_rads:
    - -0.011058957910473602
    - 0.038641608889295687
    - -0.04046385089854386
  accel_stddev_mps2:
    - 0.066769164676144355
    - 0.090134488179486036
    - 0.062606674918273444
  gyro_stddev_rads:
    - 0.031548249401830597
    - 0.019356758008316211
    - 0.025278031290011823
  accel_cov_mps2_2:
    -
      - 0.0044581213515500822
      - -0.0003683778242198493
      - -0.00029380846053537828
    -
      - -0.00036837782421984914
      - 0.0081242259593779075
      - 1.2505934763080379e-05
    -
      - -0.0002938084605353785
      - 1.2505934763080379e-05
      - 0.003919595744322369
  gyro_cov_rads2_2:
    -
      - 0.00099529204032010473
      - 0.0002013345169473374
      - 0.00039664428582106493
    -
      - 0.0002013345169473374
      - 0.00037468408059251375
      - 0.00012786833659219509
    -
      - 0.00039664428582106493
      - 0.00012786833659219509
      - 0.00063897886589881685
  stationary_samples: 7890
  method: bootstrap_rest
calibrated_noise:
  accel_stddev_mps2:
    - 0.18027756377319928
    - 0.18027756377319942
    - 0.18027756377319951
  gyro_stddev_rads:
    - 0.019999999999999993
    - 0.020000000000000018
    - 0.020000000000000014
  accel_cov_mps2_2:
    -
      - 0.032499999999999932
      - -0.00023989374898884203
      - -0.00026387438696203749
    -
      - -0.0002398937489888429
      - 0.03249999999999998
      - 0.0019476158818247779
    -
      - -0.00026387438696203619
      - 0.0019476158818247762
      - 0.032500000000000015
  gyro_cov_rads2_2:
    -
      - 0.0003999999999999998
      - 4.3010063151678389e-07
      - 8.6321518089700287e-07
    -
      - 4.3010063151678727e-07
      - 0.00040000000000000072
      - 1.1044245665069055e-05
    -
      - 8.6321518089700287e-07
      - 1.1044245665069028e-05
      - 0.00040000000000000051
  stationary_samples: 6745
  method: bootstrap_rest
  phase: bootstrap
stability:
  gyro_bias_stddev_rads:
    - 0.020382604823478558
    - 0.014720816178741209
    - 0.015981120453088176
  accel_bias_stddev_mps2:
    - 2.937642265032828
    - 3.3437548010833535
    - 4.5019472815987829
accel_calibration:
  bias_mps2:
    - -0.10696757275280554
    - -0.46342925587704553
    - -2.1711286069629305
  A:
    -
      - 1.0139959959429994
      - 0
      - 0
    -
      - -0.022703432079192724
      - 1.0017137901689082
      - 0
    -
      - 0.037391924915678297
      - -0.023179654053384319
      - 0.95932091429448541
  bias_cov_mps2_2:
    -
      - 0.0044566083377412134
      - 0.00041077464707389862
      - 0.00054613613225294115
    -
      - 0.00041077464707389862
      - 0.004084990139501002
      - 0.00092910329199557694
    -
      - 0.00054613613225294115
      - 0.00092910329199557694
      - 0.0055186115138894905
  param_cov:
    -
      - 0.0044566083377412247
      - 0.00041077464707389916
      - 0.00054613613225294028
      - 0.00018233973561621706
      - 0.00011066244007454907
      - -2.4573021714393287e-05
      - 0.00056943649729657283
      - -1.5302758135410235e-05
      - 4.9823810617183479e-05
    -
      - 0.00041077464707389922
      - 0.0040849901395010055
      - 0.00092910329199557358
      - 3.0580278593282323e-05
      - 0.00010280460947112781
      - -5.1085716229551412e-05
      - 8.5326896770937215e-05
      - 0.00010991098196616841
      - 9.3919296276992475e-06
    -
      - 0.0005461361322529405
      - 0.00092910329199557347
      - 0.0055186115138894931
      - 5.5212382190708795e-05
      - 4.7194853584796306e-05
      - -1.1194920804230692e-05
      - 0.00062696803599440938
      - -0.00013536155984780973
      - 0.0001028975088049649
    -
      - 0.00018233973561621706
      - 3.0580278593282316e-05
      - 5.5212382190708795e-05
      - 5.5657659806512926e-05
      - 3.4296278773710508e-05
      - -6.6636111301269825e-06
      - 2.0512639155336567e-05
      - -4.9232920249454241e-06
      - -1.6893693787261782e-06
    -
      - 0.00011066244007454909
      - 0.00010280460947112782
      - 4.719485358479632e-05
      - 3.4296278773710508e-05
      - 0.00045317144362422171
      - -8.874449795218507e-06
      - 5.5386355189415892e-05
      - -1.2189295163922695e-05
      - -2.3461354249551224e-06
    -
      - -2.4573021714393291e-05
      - -5.1085716229551412e-05
      - -1.119492080423069e-05
      - -6.6636111301269833e-06
      - -8.874449795218507e-06
      - 5.8180275945422988e-05
      - -7.0432704081902065e-06
      - 1.4385751871399052e-05
      - -1.0188493478662167e-05
    -
      - 0.00056943649729657283
      - 8.5326896770937229e-05
      - 0.00062696803599440938
      - 2.051263915533657e-05
      - 5.5386355189415872e-05
      - -7.0432704081902065e-06
      - 0.00069163390352627711
      - -2.4711352984763158e-05
      - 2.1849961997801359e-05
    -
      - -1.5302758135410238e-05
      - 0.00010991098196616841
      - -0.00013536155984780973
      - -4.9232920249454241e-06
      - -1.21892951639227e-05
      - 1.4385751871399051e-05
      - -2.4711352984763158e-05
      - 0.00028930613166126915
      - 3.8332118221657302e-05
    -
      - 4.9823810617183486e-05
      - 9.3919296276992425e-06
      - 0.0001028975088049649
      - -1.6893693787261795e-06
      - -2.3461354249551224e-06
      - -1.0188493478662167e-05
      - 2.1849961997801362e-05
      - 3.8332118221657302e-05
      - 6.4813529305870975e-05
  bias_stddev_mps2:
    - 0.066757833530913913
    - 0.063913927586254651
    - 0.074287357698934839
  A_stddev:
    -
      - 0.0074604061421958733
      - 0
      - 0
    -
      - 0.021287823834864394
      - 0.007627599618846217
      - 0
    -
      - 0.026298933505491711
      - 0.017009001489248853
      - 0.0080506850209079127
ellipsoid:
  W:
    -
      - 1.0301014816655094
      - -0.023609072881826065
      - 0.035870855597339255
    -
      - -0.023609072881826065
      - 1.0039678137765939
      - -0.022236726919522519
    -
      - 0.035870855597339255
      - -0.022236726919522519
      - 0.92029661660280737
  center:
    - -0.10696757275280554
    - -0.46342925587704553
    - -2.1711286069629305
fit_quality:
  rms_residual_mps2: 1.3623235089262717
  num_clusters: 22
  num_samples: 2476
noise_fit:
  stationary_samples: 7890
  method: ""
  phase: bootstrap