version: 1
frame_id: imu_link
created_unix_ns: 1767420313738915978
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 27.815404926233146
  stddev_c: 2.1878341441550559
noise:
  accel_stddev_mps2:
    - 0.078007544014448343
    - 0.089048607446403541
    - 0.084231078129754222
  gyro_stddev_rads:
    - 0.047683163876056582
    - 0.043949049475661653
    - 0.029957500614421213
  gyro_cov_rads2_2:
    -
      - 0.0022736841172308702
      - 0.00010433522137910004
      - 0.0002149330277046518
    -
      - 0.00010433522137910011
      - 0.0019315189498141561
      - 0.00018715874715380436
    -
      - 0.00021493302770465183
      - 0.00018715874715380436
      - 0.00089745184306304847
raw:
  accel_bias_mps2:
    - 1.7164384604217
    - -2.0847561699969059
    - -0.030383987523190728
  gyro_bias_rads:
    - -0.015322735018966763
    - 0.034700102287699944
    - -0.039635806337124449
  accel_stddev_mps2:
    - 0.078007544014448343
    - 0.089048607446403541
    - 0.084231078129754222
  gyro_stddev_rads:
    - 0.047683163876056582
    - 0.043949049475661653
    - 0.029957500614421213
  gyro_cov_rads2_2:
    -
      - 0.0022736841172308671
      - 0.00010433522137909886
      - 0.00021493302770465137
    -
      - 0.00010433522137909901
      - 0.0019315189498141561
      - 0.00018715874715380458
    -
      - 0.0002149330277046514
      - 0.00018715874715380463
      - 0.00089745184306304728
  stationary_samples: 1038
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.031868884290616344
    - 0.03223520845840943
    - 0.020310141370871018
  accel_bias_stddev_mps2:
    - 3.3557508040145239
    - 5.6616082828565135
    - 6.8152456832534307
accel_calibration:
  bias_mps2:
    - 0.019998328541921098
    - -0.51769670490045916
    - -2.2643757396662592
  A:
    -
      - 0.99134422838920222
      - 0
      - 0
    -
      - -0.0018362232279598904
      - 1.0020082094483465
      - 0
    -
      - -0.0071159629342865604
      - -0.0029466959439860153
      - 0.96385563378480077
  bias_stddev_mps2:
    - 0.053683247237832646
    - 0.010757440786800052
    - 0.014062920258078249
  A_stddev:
    -
      - 0.0061199632283497679
      - 0
      - 0
    -
      - 0.0069544967828246915
      - 0.0012378450775559153
      - 0
    -
      - 0.003438831829231449
      - 0.002406988698134912
      - 0.0013356255945134892
ellipsoid:
  W:
    -
      - 0.98281738780480787
      - -0.0018189421696795357
      - -0.0068587609640159237
    -
      - -0.0018189421696795357
      - 1.0040291348188677
      - -0.0028401894866617425
    -
      - -0.0068587609640159237
      - -0.0028401894866617425
      - 0.9290176827787
  center:
    - 0.019998328541921098
    - -0.51769670490045916
    - -2.2643757396662592
fit_quality:
  rms_residual_mps2: 0.021030813706217132
  num_clusters: 23
  num_samples: 1858
noise_fit:
  stationary_samples: 1038
  method: bootstrap_rest
  phase: bootstrap