version: 1
frame_id: imu_link
created_unix_ns: 1767426558823022165
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 27.105861878147302
  stddev_c: 1.8141266534400367
raw_noise:
  accel_bias_mps2:
    - 3.0471787719249477
    - 1.0504380542740896
    - 1.1668768775030651
  gyro_bias_rads:
    - -0.012920121589803666
    - 0.038034098283840322
    - -0.038993771802720616
  accel_stddev_mps2:
    - 0.22225077780699454
    - 0.16976504974987253
    - 0.14572102236124723
  gyro_stddev_rads:
    - 0.098366645646764811
    - 0.070591318719591817
    - 0.047960234983616394
  accel_cov_mps2_2:
    -
      - 0.049395408235814051
      - 0.0095882826676395982
      - -0.001952087406237681
    -
      - 0.0095882826676395947
      - 0.028820172116576691
      - 0.00047040739583615281
    -
      - -0.0019520874062376814
      - 0.00047040739583615286
      - 0.021234616358007115
  gyro_cov_rads2_2:
    -
      - 0.0096759969757961948
      - 0.0017760919084546744
      - 0.0007055508307245241
    -
      - 0.0017760919084546748
      - 0.0049831342785709946
      - 0.00049693780836225141
    -
      - 0.00070555083072452421
      - 0.0004969378083622513
      - 0.0023001841396837015
  stationary_samples: 1663
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.05012456424914196
    - 0.054172167826149829
    - 0.027011156213822166
  accel_bias_stddev_mps2:
    - 5.1203200111359539
    - 4.9310255769363174
    - 5.0422457462416199
accel_calibration:
  bias_mps2:
    - -0.054586765583132406
    - -0.36860916241077379
    - -2.2255247314870701
  A:
    -
      - 1.0042851609073784
      - 0
      - 0
    -
      - -0.031449397790812128
      - 1.023759144112802
      - 0
    -
      - 0.014443104690242459
      - 0.0014429098954544311
      - 0.96659923435616846
  bias_stddev_mps2:
    - 0.098307356374810945
    - 0.14061301405701529
    - 0.13888750485193044
  A_stddev:
    -
      - 0.0092486823515397672
      - 0
      - 0
    -
      - 0.027814186395074061
      - 0.016390497358217022
      - 0
    -
      - 0.02810284627051253
      - 0.023691365721882247
      - 0.011884684647036348
ellipsoid:
  W:
    -
      - 1.0097863523132571
      - -0.032175768466506237
      - 0.013960693935314347
    -
      - -0.032175768466506237
      - 1.0480848671435432
      - 0.0013947156001911922
    -
      - 0.013960693935314347
      - 0.0013947156001911922
      - 0.93431407985793102
  center:
    - -0.054586765583132406
    - -0.36860916241077379
    - -2.2255247314870701
fit_quality:
  rms_residual_mps2: 0.11895871393286478
  num_clusters: 19
  num_samples: 2126
noise_fit:
  stationary_samples: 1663
  method: bootstrap_rest
  phase: bootstrap