version: 1
frame_id: imu_link
created_unix_ns: 1767432454447730192
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 31.425887844429372
  stddev_c: 0.35591635733153354
raw_noise:
  accel_bias_mps2:
    - 0.63364713383013016
    - -1.5251777002951514
    - -0.67301800253388022
  gyro_bias_rads:
    - -0.010424880895940545
    - 0.042151837463209649
    - -0.038854974772491523
  accel_stddev_mps2:
    - 0.16618430861361561
    - 0.1465880887691326
    - 0.10555466652478747
  gyro_stddev_rads:
    - 0.034661521972293073
    - 0.031933245202807867
    - 0.054517021762587124
  accel_cov_mps2_2:
    -
      - 0.027617224429385436
      - 0.0063491934397484004
      - -0.0027122241728919274
    -
      - 0.0063491934397483995
      - 0.021488067768987099
      - -0.001473286787705774
    -
      - -0.0027122241728919283
      - -0.0014732867877057742
      - 0.01114178762515909
  gyro_cov_rads2_2:
    -
      - 0.0012014211054357557
      - 7.4003037288369538e-05
      - 6.6317155491741726e-07
    -
      - 7.4003037288369566e-05
      - 0.0010197321491826514
      - 3.5672858217100847e-05
    -
      - 6.6317155491741609e-07
      - 3.5672858217100853e-05
      - 0.0029721056618623983
  stationary_samples: 1724
  method: bootstrap_rest
calibrated_noise:
  accel_stddev_mps2:
    - 0.15000000000000008
    - 0.15000000000000008
    - 0.15000000000000008
  gyro_stddev_rads:
    - 0.02
    - 0.02
    - 0.02
  accel_cov_mps2_2:
    -
      - 0.022500000000000023
      - 0.00048377625878239839
      - -0.00033640751174812792
    -
      - 0.00048377625878239883
      - 0.02250000000000002
      - -0.00082561475607705363
    -
      - -0.00033640751174812775
      - -0.00082561475607705395
      - 0.022500000000000027
  gyro_cov_rads2_2:
    -
      - 0.00039999999999999996
      - -1.0661609529918797e-05
      - -9.8536511070493176e-06
    -
      - -1.0661609529918804e-05
      - 0.00040000000000000002
      - 9.9305322162557454e-05
    -
      - -9.8536511070493176e-06
      - 9.9305322162557426e-05
      - 0.00040000000000000007
  stationary_samples: 352
  method: bootstrap_rest
  phase: bootstrap
stability:
  gyro_bias_stddev_rads:
    - 0.021512755469668712
    - 0.014398957713854254
    - 0.028022722717435271
  accel_bias_stddev_mps2:
    - 4.882232333609636
    - 5.4018555370996699
    - 6.5440913452820748
accel_calibration:
  bias_mps2:
    - 0.039636967638510406
    - -0.51471603468990701
    - -2.2123031377315518
  A:
    -
      - 0.99458502538673232
      - 0
      - 0
    -
      - 0.00016811244378268914
      - 1.0035485856811055
      - 0
    -
      - -0.0015378809889387212
      - 0.0054087400050010512
      - 0.96760352243054282
  bias_stddev_mps2:
    - 0.0091059141458972575
    - 0.0080696587520781675
    - 0.0067075350374485232
  A_stddev:
    -
      - 0.0010043833640507416
      - 0
      - 0
    -
      - 0.0039252618316628577
      - 0.001
      - 0
    -
      - 0.0033218760004383543
      - 0.0020017574421535493
      - 0.001
ellipsoid:
  W:
    -
      - 0.98920176606325694
      - 0.00016039100676570859
      - -0.0014880590619760733
    -
      - 0.00016039100676570859
      - 1.007139018290989
      - 0.0052335158807500087
    -
      - -0.0014880590619760733
      - 0.0052335158807500087
      - 0.93625657661999395
  center:
    - 0.039636967638510406
    - -0.51471603468990701
    - -2.2123031377315518
fit_quality:
  rms_residual_mps2: 0.11306587152608431
  num_clusters: 15
  num_samples: 1821
noise_fit:
  stationary_samples: 1724
  method: ""
  phase: bootstrap