version: 1
frame_id: imu_link
created_unix_ns: 1767217532931012517
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 26.782778338064322
  stddev_c: 1.5177865815932092
noise:
  accel_stddev_mps2:
    - 0.042410971393184102
    - 0.051878577600672555
    - 0.070285913405542522
  gyro_stddev_rads:
    - 0.068582494076594849
    - 0.037401645417077363
    - 0.02100750944147612
accel_calibration:
  bias_mps2:
    - -0.018119634258938245
    - -0.57570930777040163
    - -2.1898770708660966
  A:
    -
      - 0.99444589045237075
      - 0
      - 0
    -
      - 0.0087181675766972479
      - 1.014763732245721
      - 0
    -
      - 0.0030894773685510007
      - 0.0036257124205775564
      - 0.96385879666189367
  bias_stddev_mps2:
    - 0.02622525943429237
    - 0.024701116685604953
    - 0.018364678661697276
  A_stddev:
    -
      - 0.0034709915379133971
      - 0
      - 0
    -
      - 0.0053985729038634103
      - 0.0039486444252710175
      - 0
    -
      - 0.0057080874985248999
      - 0.0048777783468138321
      - 0.0020440959975900142
ellipsoid:
  W:
    -
      - 0.98900818035391469
      - 0.0088580818249411816
      - 0.0029778199387657214
    -
      - 0.0088580818249411816
      - 1.0297585780718221
      - 0.0034946748107399653
    -
      - 0.0029778199387657214
      - 0.0034946748107399653
      - 0.92902377990251372
  center:
    - -0.018119634258938245
    - -0.57570930777040163
    - -2.1898770708660966
fit_quality:
  rms_residual_mps2: 0.050278481006001137
  num_clusters: 30
  num_samples: 11957