version: 1
frame_id: imu_link
created_unix_ns: 1767219211400602147
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 29.431953169617369
  stddev_c: 1.655096343199153
noise:
  accel_stddev_mps2:
    - 1.4745802555879346
    - 1.4033339614930573
    - 0.40143978941606828
  gyro_stddev_rads:
    - 0.18681883060941809
    - 0.34530363959327892
    - 0.64477864441939925
accel_calibration:
  bias_mps2:
    - 0.007202371809400465
    - -0.51832404992410519
    - -2.1965047551895647
  A:
    -
      - 0.99460740196124653
      - 0
      - 0
    -
      - -0.002759235935142418
      - 1.0030224135890886
      - 0
    -
      - -0.010825111916162932
      - 0.0014674464366112951
      - 0.97186382966182006
  bias_stddev_mps2:
    - 0.02015210912451891
    - 0.015318663103792984
    - 0.014913218069365051
  A_stddev:
    -
      - 0.0024547889168510082
      - 0
      - 0
    -
      - 0.004988183562902042
      - 0.0020790602185330673
      - 0
    -
      - 0.0058023025831691168
      - 0.0036838717110252877
      - 0.0022851531545027117
ellipsoid:
  W:
    -
      - 0.98936868046704385
      - -0.0027834607592355856
      - -0.01052053472335991
    -
      - -0.0027834607592355856
      - 1.0060561155611252
      - 0.0014261581137086446
    -
      - -0.01052053472335991
      - 0.0014261581137086446
      - 0.94451930340493917
  center:
    - 0.007202371809400465
    - -0.51832404992410519
    - -2.1965047551895647
fit_quality:
  rms_residual_mps2: 0.040380799479217022
  num_clusters: 33
  num_samples: 2060
noise_fit:
  stationary_samples: 200
  method: rest_baseline