version: 1
frame_id: imu_link
created_unix_ns: 1767422334821053037
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 26.780945033751202
  stddev_c: 1.1748336267584552
noise:
  accel_stddev_mps2:
    - 0.1312298609745807
    - 0.14789432225301688
    - 0.086251426030236139
  gyro_stddev_rads:
    - 0.028560488214503861
    - 0.02512846181200537
    - 0.039096610740910656
  accel_cov_mps2_2:
    -
      - 9.9999999999999995e-07
      - 0
      - 0
    -
      - 0
      - 9.9999999999999995e-07
      - 0
    -
      - 0
      - 0
      - 9.9999999999999995e-07
  gyro_cov_rads2_2:
    -
      - 0.00081570148705081402
      - -6.344028345617516e-05
      - 4.0869772482513948e-05
    -
      - -6.344028345617516e-05
      - 0.00063143959303741163
      - -0.000105268064020505
    -
      - 4.0869772482513948e-05
      - -0.000105268064020505
      - 0.0015285449714262898
raw:
  accel_bias_mps2:
    - 1.6594618248357687
    - -2.0254938353590273
    - 1.5716589014652267
  gyro_bias_rads:
    - -0.010702400134895684
    - 0.037701964789239512
    - -0.040928099054470861
  accel_stddev_mps2:
    - 0.1312298609745807
    - 0.14789432225301688
    - 0.086251426030236139
  gyro_stddev_rads:
    - 0.028560488214503861
    - 0.02512846181200537
    - 0.039096610740910656
  accel_cov_mps2_2:
    -
      - 9.9999999999999995e-07
      - 0
      - 0
    -
      - 0
      - 9.9999999999999995e-07
      - 0
    -
      - 0
      - 0
      - 9.9999999999999995e-07
  gyro_cov_rads2_2:
    -
      - 0.00081570148705081391
      - -6.3440283456175255e-05
      - 4.0869772482514049e-05
    -
      - -6.3440283456175255e-05
      - 0.00063143959303741217
      - -0.00010526806402050508
    -
      - 4.0869772482514056e-05
      - -0.00010526806402050509
      - 0.0015285449714262907
  stationary_samples: 2179
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.018431767385233326
    - 0.017213696700562747
    - 0.024334955125990161
  accel_bias_stddev_mps2:
    - 4.1481506913942781
    - 4.8015388237586087
    - 6.3774988912981847
accel_calibration:
  bias_mps2:
    - 0.060975087109444201
    - -0.59648743014177519
    - -2.1487114501789546
  A:
    -
      - 1.003711840824812
      - 0
      - 0
    -
      - -0.0060224629797094118
      - 0.99928199842105148
      - 0
    -
      - 0.017387485723046353
      - -0.013508577605890224
      - 0.98082426194105998
  bias_stddev_mps2:
    - 0.1185687325689174
    - 0.090206734778775638
    - 0.080272129335496392
  A_stddev:
    -
      - 0.012637928125244037
      - 0
      - 0
    -
      - 0.047292063136816297
      - 0.011902900596266704
      - 0
    -
      - 0.035327239586400348
      - 0.018578675489643155
      - 0.009676632728127783
ellipsoid:
  W:
    -
      - 1.007776054132044
      - -0.0062530190420419015
      - 0.017054067851317658
    -
      - -0.0062530190420419015
      - 0.9987469940373046
      - -0.013249540660170811
    -
      - 0.017054067851317658
      - -0.013249540660170811
      - 0.96201623281222504
  center:
    - 0.060975087109444201
    - -0.59648743014177519
    - -2.1487114501789546
fit_quality:
  rms_residual_mps2: 0.12707592795665765
  num_clusters: 16
  num_samples: 4880
noise_fit:
  stationary_samples: 2179
  method: bootstrap_rest
  phase: bootstrap