version: 1
frame_id: imu_link
created_unix_ns: 1767429603308615134
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 28.987019787319969
  stddev_c: 1.436595573405183
raw_noise:
  accel_bias_mps2:
    - -0.066770977731688039
    - -1.261509600276703
    - 0.78173500911937022
  gyro_bias_rads:
    - -0.016015110685560406
    - 0.038563952967068486
    - -0.044123222409826357
  accel_stddev_mps2:
    - 0.19855902758572644
    - 0.20258027669378445
    - 0.25462963616239814
  gyro_stddev_rads:
    - 0.10766146605738396
    - 0.088632046555123176
    - 0.10794602316666317
  accel_cov_mps2_2:
    -
      - 0.039425687435789274
      - 0.0076295873558425839
      - -0.001295278056131953
    -
      - 0.0076295873558425813
      - 0.041038768505330267
      - 0.0035784871288685439
    -
      - -0.0012952780561319528
      - 0.0035784871288685439
      - 0.06483625161219525
  gyro_cov_rads2_2:
    -
      - 0.011590991273625237
      - -0.00023548081892789147
      - 0.00067399144591070038
    -
      - -0.00023548081892789142
      - 0.0078556396765495223
      - 0.00027293411591827407
    -
      - 0.00067399144591070179
      - 0.00027293411591827396
      - 0.011652343917497782
  stationary_samples: 1564
  method: bootstrap_rest
calibrated_noise:
  accel_stddev_mps2:
    - 0.041979301775624561
    - 0.047931705944006253
    - 0.068893463416771689
  gyro_stddev_rads:
    - 0.00263927186015503
    - 0.006918305545248425
    - 0.0053194095680530818
  accel_cov_mps2_2:
    -
      - 0.0017622617775689552
      - 0.00045786517328825886
      - -0.00036089675317687328
    -
      - 0.0004578651732882588
      - 0.0022974484347026846
      - -0.0015423438033835056
    -
      - -0.00036089675317687323
      - -0.0015423438033835058
      - 0.0047463093015580587
  gyro_cov_rads2_2:
    -
      - 6.9657559518061927e-06
      - -6.6254288364325654e-07
      - -4.3390785706986429e-07
    -
      - -6.6254288364325654e-07
      - 4.7862951617415107e-05
      - 3.4531563213313374e-05
    -
      - -4.3390785706986424e-07
      - 3.4531563213313374e-05
      - 2.8296118152694678e-05
  stationary_samples: 241
  method: bootstrap_rest
  phase: bootstrap
stability:
  gyro_bias_stddev_rads:
    - 0.062803788180329653
    - 0.049240417279511832
    - 0.05542307006133404
  accel_bias_stddev_mps2:
    - 5.4301410060238577
    - 5.3141195709670139
    - 5.6850167418686439
accel_calibration:
  bias_mps2:
    - 0.34766534940725646
    - -0.41037089172533858
    - -2.3980365036994118
  A:
    -
      - 1.0284905713753592
      - 0
      - 0
    -
      - 0.016508976198389435
      - 0.99076192933274632
      - 0
    -
      - 0.14758788452505747
      - 0.017384815661186364
      - 0.96896487111336826
  bias_stddev_mps2:
    - 0.17613487465209543
    - 0.18677248430314594
    - 0.18127460738191001
  A_stddev:
    -
      - 0.021373262055737023
      - 0
      - 0
    -
      - 0.039554585931354608
      - 0.019551333547853267
      - 0
    -
      - 0.059258410866819808
      - 0.067293754831155975
      - 0.018964397965749284
ellipsoid:
  W:
    -
      - 1.0798475853617133
      - 0.018922253275917289
      - 0.143007475506717
    -
      - 0.018922253275917289
      - 0.98191143243071921
      - 0.016845275666471111
    -
      - 0.143007475506717
      - 0.016845275666471111
      - 0.93889292145174641
  center:
    - 0.34766534940725646
    - -0.41037089172533858
    - -2.3980365036994118
fit_quality:
  rms_residual_mps2: 0.25736998743649153
  num_clusters: 18
  num_samples: 1748
noise_fit:
  stationary_samples: 1564
  method: ""
  phase: bootstrap