version: 1
frame_id: imu_link
created_unix_ns: 1767439031768317075
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 29.841702592652236
  stddev_c: 1.7337435784155626
raw_noise:
  accel_bias_mps2:
    - 1.8154574801093974
    - 0.27895742040631633
    - -0.23713313850618919
  gyro_bias_rads:
    - -0.0085876845790348912
    - 0.040997647904145729
    - -0.041195704376704091
  accel_stddev_mps2:
    - 0.1484576398965004
    - 0.13606538936220769
    - 0.13150533988915922
  gyro_stddev_rads:
    - 0.085886716326834783
    - 0.14494376677036391
    - 0.065507541906928923
  accel_cov_mps2_2:
    -
      - 0.022039670843638989
      - -0.0043914910772432612
      - -0.00033045934630433239
    -
      - -0.0043914910772432578
      - 0.018513790182289179
      - 0.001849344288472124
    -
      - -0.00033045934630433196
      - 0.001849344288472124
      - 0.017293654419363289
  gyro_cov_rads2_2:
    -
      - 0.0073765280414061895
      - 0.0047615462738454812
      - -0.002475103420200788
    -
      - 0.0047615462738454821
      - 0.021008695525581648
      - -0.0042460186716728084
    -
      - -0.0024751034202007876
      - -0.0042460186716728084
      - 0.0042912380466880494
  stationary_samples: 2225
  method: bootstrap_rest
calibrated_noise:
  accel_stddev_mps2:
    - 0.18160091472758805
    - 0.18043898948543741
    - 0.18031315510303417
  gyro_stddev_rads:
    - 0.020000000000000018
    - 0.024786402774194187
    - 0.020000000000000014
  accel_cov_mps2_2:
    -
      - 0.032978892229896702
      - -0.0013844540019747418
      - -0.0021291280157052124
    -
      - -0.0013844540019747418
      - 0.032558228926525788
      - -0.00021519912722926804
    -
      - -0.0021291280157052107
      - -0.0002151991272292663
      - 0.032512833903210858
  gyro_cov_rads2_2:
    -
      - 0.00040000000000000072
      - -2.3460674981627102e-05
      - 1.5246194856934144e-05
    -
      - -2.3460674981627105e-05
      - 0.0006143657624845813
      - -0.00037664560038635315
    -
      - 1.5246194856934141e-05
      - -0.0003766456003863531
      - 0.00040000000000000056
  stationary_samples: 500
  method: bootstrap_rest
  phase: bootstrap
stability:
  gyro_bias_stddev_rads:
    - 0.034496155964814409
    - 0.069522113443943059
    - 0.024404213548655025
  accel_bias_stddev_mps2:
    - 5.5426603633148792
    - 4.8046111233300497
    - 6.1534485552329956
accel_calibration:
  bias_mps2:
    - -0.028497399045275883
    - -0.53845447807735691
    - -2.168229949693063
  A:
    -
      - 0.98765773701693504
      - 0
      - 0
    -
      - -0.0092325135845425007
      - 1.0041131745758147
      - 0
    -
      - 0.0061598214501305103
      - 0.0021727290956610225
      - 0.96743666009223128
  bias_cov_mps2_2:
    -
      - 0.00038411573407921981
      - 8.5057073896473449e-05
      - 2.0040437822647838e-05
    -
      - 8.5057073896473449e-05
      - 0.00059474935126097343
      - 9.1795714477036004e-05
    -
      - 2.0040437822647824e-05
      - 9.1795714477035977e-05
      - 0.00044006006704145272
  param_cov:
    -
      - 0.00038411573407921926
      - 8.5057073896473368e-05
      - 2.0040437822647631e-05
      - 1.5638493638596608e-05
      - 7.740329704505311e-05
      - 5.2379564263688475e-07
      - 9.2821968281488573e-06
      - 1.3054163075662785e-05
      - 4.8315959160591801e-06
    -
      - 8.5057073896473354e-05
      - 0.00059474935126097321
      - 9.1795714477036045e-05
      - 5.8506478452406651e-06
      - 0.00011291151531444796
      - 3.777670186412588e-06
      - 1.1778627197867742e-05
      - 3.8047226600130888e-05
      - 1.0138057821468057e-05
    -
      - 2.0040437822647614e-05
      - 9.1795714477036058e-05
      - 0.00044006006704145278
      - -3.6838520322981095e-06
      - 4.220771990237969e-05
      - -2.4543842056691306e-06
      - 2.6375413268979731e-05
      - 3.6548701701898623e-05
      - 2.3493664201655468e-05
    -
      - 1.5638493638596608e-05
      - 5.8506478452406651e-06
      - -3.6838520322981099e-06
      - 5.179246814114602e-06
      - 4.8957450523649763e-06
      - 1.8789944429021019e-07
      - 6.5393593652026682e-07
      - 1.0064537097235967e-06
      - -1.5500800090090205e-06
    -
      - 7.7403297045053123e-05
      - 0.00011291151531444796
      - 4.2207719902379684e-05
      - 4.8957450523649771e-06
      - 0.00012779902053105323
      - -1.5650758949701385e-06
      - 1.1687896349228062e-05
      - 1.7333870305269368e-05
      - 1.7309928538671324e-06
    -
      - 5.2379564263688443e-07
      - 3.777670186412588e-06
      - -2.4543842056691301e-06
      - 1.8789944429021017e-07
      - -1.5650758949701387e-06
      - 7.337090799402902e-06
      - 6.7773197557137967e-07
      - -1.0496858125292894e-06
      - -1.5460469310051887e-06
    -
      - 9.2821968281488573e-06
      - 1.177862719786774e-05
      - 2.6375413268979731e-05
      - 6.5393593652026682e-07
      - 1.1687896349228062e-05
      - 6.7773197557137988e-07
      - 1.501984695407775e-05
      - 2.3411579581357661e-06
      - -4.819521918383155e-07
    -
      - 1.3054163075662785e-05
      - 3.8047226600130888e-05
      - 3.6548701701898623e-05
      - 1.0064537097235967e-06
      - 1.7333870305269368e-05
      - -1.0496858125292894e-06
      - 2.3411579581357661e-06
      - 2.6432881975563577e-05
      - 2.025853178425217e-06
    -
      - 4.8315959160591801e-06
      - 1.0138057821468057e-05
      - 2.3493664201655468e-05
      - -1.5500800090090209e-06
      - 1.7309928538671322e-06
      - -1.5460469310051885e-06
      - -4.8195219183831592e-07
      - 2.025853178425217e-06
      - 6.0846940892079631e-06
  bias_stddev_mps2:
    - 0.019598870734795413
    - 0.024387483495862661
    - 0.020977608706462543
  A_stddev:
    -
      - 0.0022757958638934743
      - 0
      - 0
    -
      - 0.011304822888088656
      - 0.002708706480850758
      - 0
    -
      - 0.0038755447299802601
      - 0.0051412918586249802
      - 0.002466717269815889
ellipsoid:
  W:
    -
      - 0.97559098819679957
      - -0.0092571049014005292
      - 0.0059592370904787461
    -
      - -0.0092571049014005292
      - 1.0082479881084436
      - 0.0021019777795915138
    -
      - 0.0059592370904787461
      - 0.0021019777795915138
      - 0.93593369129041148
  center:
    - -0.028497399045275883
    - -0.53845447807735691
    - -2.168229949693063
fit_quality:
  rms_residual_mps2: 0.39500587195139975
  num_clusters: 22
  num_samples: 2557
noise_fit:
  stationary_samples: 2225
  method: ""
  phase: bootstrap