version: 2
created_unix_ns: 1767499217825013869
gravity_mps2: 9.8066499999999994
fit_sample_count: 134
calib:
  valid: true
  accel_bias_mps2:
    - -0.33790069316465443
    - 0.91894998541533002
    - 1.5027644465796619
  accel_A_row_major:
    - 1
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 1
  accel_param_cov_row_major_12x12:
    - 0.0025000000000000005
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0025000000000000005
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0025000000000000005
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0001
  rms_residual_mps2: 2.6843041025727326
  gyro_bias_rads:
    - -0.038629443560804395
    - -0.011766899785365981
    - -0.041646909585995005
  gyro_bias_cov_row_major:
    - 8.3543239595979137e-09
    - -3.1371125125264006e-10
    - 3.6177398171351749e-09
    - -3.1371125125264006e-10
    - 2.6443590486832488e-08
    - 1.7689779550772433e-09
    - 3.6177398171351749e-09
    - 1.7689779550772433e-09
    - 4.8500008215916803e-09
  temperature_c: 26.192830003449362
  temperature_var_c2: 3.9695978734218649
measurement_noise:
  accel_cov_raw_mps2_2:
    - 18.021026276477066
    - -0.15172516897586583
    - 0.38446265099634241
    - -0.15172516897586583
    - 2.4354809531198809
    - 0.54308761314817755
    - 0.38446265099634241
    - 0.54308761314817755
    - 3.5344501047757086
  gyro_cov_raw_rads2_2:
    - 0.2395445565626223
    - 0.061205370191438957
    - -0.049124684927775622
    - 0.061205370191438957
    - 0.65750146089284545
    - 0.10711517832976861
    - -0.049124684927775622
    - 0.10711517832976861
    - 0.29096860999091506
  accel_cov_corrected_mps2_2:
    - 18.021026276477066
    - -0.15172516897586583
    - 0.38446265099634241
    - -0.15172516897586583
    - 2.4354809531198809
    - 0.54308761314817755
    - 0.38446265099634241
    - 0.54308761314817755
    - 3.5344501047757086
  gyro_cov_corrected_rads2_2:
    - 0.2395445565626223
    - 0.061205370191438957
    - -0.049124684927775622
    - 0.061205370191438957
    - 0.65750146089284545
    - 0.10711517832976861
    - -0.049124684927775622
    - 0.10711517832976861
    - 0.29096860999091506
accel_ellipsoid:
  center_mps2:
    - -0.33790069316465443
    - 0.91894998541533002
    - 1.5027644465796619
  Q_row_major:
    - 0.010398211550100477
    - 0
    - 0
    - 0
    - 0.010398211550100477
    - 0
    - 0
    - 0
    - 0.010398211550100477
