version: 1
frame_id: imu_link
created_unix_ns: 1767423562647448188
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 27.175018219677256
  stddev_c: 2.8008832974435238
noise:
  accel_stddev_mps2:
    - 0.12811232697860067
    - 0.16544033784757106
    - 0.10949858711073167
  gyro_stddev_rads:
    - 0.045261181779770211
    - 0.027570051157961354
    - 0.025616334183611134
  accel_cov_mps2_2:
    -
      - 0.016412768323871892
      - 0
      - 0
    -
      - 0
      - 0.027370505387118455
      - 0
    -
      - 0
      - 0
      - 0.011989940579246492
  gyro_cov_rads2_2:
    -
      - 0.0020485745761014027
      - -0.00019902091839864384
      - 0.00017849469321178961
    -
      - -0.00019902091839864384
      - 0.00076010772085260622
      - -3.6461307821812821e-05
    -
      - 0.00017849469321178964
      - -3.6461307821812828e-05
      - 0.00065619657700644431
raw:
  accel_bias_mps2:
    - -1.4827313941646936
    - -2.2840538693654042
    - -0.99938046759499899
  gyro_bias_rads:
    - -0.011155780136577967
    - 0.039254958341428899
    - -0.038783561302059427
  accel_stddev_mps2:
    - 0.12811232697860067
    - 0.16544033784757106
    - 0.10949858711073167
  gyro_stddev_rads:
    - 0.045261181779770204
    - 0.027570051157961357
    - 0.025616334183611141
  accel_cov_mps2_2:
    -
      - 0.016412768323871892
      - 0
      - 0
    -
      - 0
      - 0.027370505387118455
      - 0
    -
      - 0
      - 0
      - 0.011989940579246492
  gyro_cov_rads2_2:
    -
      - 0.0020485745761014023
      - -0.00019902091839864381
      - 0.00017849469321178953
    -
      - -0.00019902091839864381
      - 0.00076010772085260644
      - -3.6461307821812868e-05
    -
      - 0.0001784946932117895
      - -3.6461307821812868e-05
      - 0.00065619657700644474
  stationary_samples: 1765
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.027839024097832222
    - 0.018170301406757496
    - 0.015805576444749503
  accel_bias_stddev_mps2:
    - 5.7768154862168917
    - 5.2180082468555282
    - 5.589304358689243
accel_calibration:
  bias_mps2:
    - 0.23514538178392083
    - -0.50012909729468569
    - -2.0570344996840264
  A:
    -
      - 1.0168836761161963
      - 0
      - 0
    -
      - 0.032714275921152197
      - 1.0017295864077382
      - 0
    -
      - 0.061960296850767517
      - -0.0061842220903304008
      - 0.96597819648352634
  bias_stddev_mps2:
    - 0.069059266850729134
    - 0.073742373805530614
    - 0.074989636190112965
  A_stddev:
    -
      - 0.0092158858808471539
      - 0
      - 0
    -
      - 0.020943690554020875
      - 0.0090509419709093111
      - 0
    -
      - 0.024560592969545287
      - 0.018495798932578474
      - 0.0087990585694186687
ellipsoid:
  W:
    -
      - 1.0389617129864699
      - 0.032387681851616473
      - 0.059852295805488322
    -
      - 0.032387681851616473
      - 1.0035004088874808
      - -0.0059738237014709435
    -
      - 0.059852295805488322
      - -0.0059738237014709435
      - 0.93311387608156626
  center:
    - 0.23514538178392083
    - -0.50012909729468569
    - -2.0570344996840264
fit_quality:
  rms_residual_mps2: 0.10869138642019287
  num_clusters: 18
  num_samples: 2260
noise_fit:
  stationary_samples: 1765
  method: bootstrap_rest
  phase: bootstrap