version: 1
frame_id: imu_link
created_unix_ns: 1767222561368446331
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 27.221549134273594
  stddev_c: 1.3933723135161895
noise:
  accel_stddev_mps2:
    - 0.10204073774985882
    - 0.093081149625229523
    - 0.097348892451956881
  gyro_stddev_rads:
    - 0.042637973262438719
    - 0.033803316103943666
    - 0.03731712979673759
raw:
  accel_bias_mps2:
    - 1.6156229755954301
    - 1.2843082954372824
    - -3.1844355844211134
  gyro_bias_rads:
    - -0.013209877506506698
    - 0.033030526333911202
    - -0.041646561057234077
  accel_stddev_mps2:
    - 0.10204073774985882
    - 0.093081149625229523
    - 0.097348892451956881
  gyro_stddev_rads:
    - 0.042637973262438719
    - 0.033803316103943666
    - 0.03731712979673759
  stationary_samples: 900
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.023419339088478694
    - 0.019569685332817058
    - 0.021957537358451767
  accel_bias_stddev_mps2:
    - 4.3702824688730804
    - 5.0695652946045486
    - 6.9457909777426146
accel_calibration:
  bias_mps2:
    - -0.059780520997233549
    - -0.53509822113641581
    - -2.1500441445851144
  A:
    -
      - 1.0120915283783263
      - 0
      - 0
    -
      - -0.011165045304975304
      - 0.99847251732224174
      - 0
    -
      - 0.015736633652795748
      - 0.008534021331993746
      - 0.96744052844291262
  bias_stddev_mps2:
    - 0.04231112636417126
    - 0.039172547739402916
    - 0.042082018068478999
  A_stddev:
    -
      - 0.0044184247106844711
      - 0
      - 0
    -
      - 0.0094142693936426804
      - 0.0046091394310807717
      - 0
    -
      - 0.016484261993082623
      - 0.0083852531554328893
      - 0.0043334523540756401
ellipsoid:
  W:
    -
      - 1.0247015616905608
      - -0.011013694124388839
      - 0.015224257176973241
    -
      - -0.011013694124388839
      - 0.99702019736790926
      - 0.0082561581071671185
    -
      - 0.015224257176973241
      - 0.0082561581071671185
      - 0.93594117607390204
  center:
    - -0.059780520997233549
    - -0.53509822113641581
    - -2.1500441445851144
fit_quality:
  rms_residual_mps2: 0.074395211489753782
  num_clusters: 27
  num_samples: 2052
noise_fit:
  stationary_samples: 900
  method: bootstrap_rest
  phase: bootstrap