version: 1
frame_id: imu_link
created_unix_ns: 1767427960268981262
has_ellipsoid: true
config:
  gravity: 9.8066499999999994
temperature:
  mean_c: 28.871192535275384
  stddev_c: 1.9636078906258734
raw_noise:
  accel_bias_mps2:
    - -0.18233290418953976
    - -0.88425036154771075
    - -0.53966075967582761
  gyro_bias_rads:
    - -0.0098423200746612042
    - 0.040675520729214175
    - -0.040783078156619461
  accel_stddev_mps2:
    - 0.14071362924732117
    - 0.16006098761628632
    - 0.14655478733035848
  gyro_stddev_rads:
    - 0.076300501020067815
    - 0.054968515152930802
    - 0.060159729231932003
  accel_cov_mps2_2:
    -
      - 0.019800325455952561
      - -0.0021009490664272859
      - 0.0027115660573008827
    -
      - -0.0021009490664272864
      - 0.025619519756700959
      - -0.0081464669381481943
    -
      - 0.0027115660573008827
      - -0.0081464669381481943
      - 0.0214783056894466
  gyro_cov_rads2_2:
    -
      - 0.0058217664559133695
      - -4.5760961572020876e-05
      - -2.9054817797082291e-05
    -
      - -4.5760961572020856e-05
      - 0.0030215376581179832
      - 0.00068968175170543177
    -
      - -2.9054817797082308e-05
      - 0.00068968175170543177
      - 0.0036191930212593742
  stationary_samples: 1740
  method: bootstrap_rest
stability:
  gyro_bias_stddev_rads:
    - 0.037932145295345519
    - 0.020551561078747282
    - 0.036399177693297542
  accel_bias_stddev_mps2:
    - 6.3104669656340251
    - 4.5466649658183682
    - 5.9914827867699145
accel_calibration:
  bias_mps2:
    - 0.14039705093485877
    - -0.54354461246051333
    - -2.2206209477832091
  A:
    -
      - 1.0028502834127782
      - 0
      - 0
    -
      - 0.02938003619671074
      - 0.99864193410414448
      - 0
    -
      - 5.0367011570102597e-05
      - -0.017903975689895137
      - 0.98926381728129742
  bias_stddev_mps2:
    - 0.084046716798709259
    - 0.1066564673412411
    - 0.091104095022026585
  A_stddev:
    -
      - 0.0093542220580180996
      - 0
      - 0
    -
      - 0.033414386687116021
      - 0.013558412809063702
      - 0
    -
      - 0.023623875462376827
      - 0.022728314291702856
      - 0.010898358466199656
ellipsoid:
  W:
    -
      - 1.0065718800048453
      - 0.029339234401782262
      - 4.9826262130890968e-05
    -
      - 0.029339234401782262
      - 0.99760626489677073
      - -0.017711755335497213
    -
      - 4.9826262130890968e-05
      - -0.017711755335497213
      - 0.9786429001819642
  center:
    - 0.14039705093485877
    - -0.54354461246051333
    - -2.2206209477832091
fit_quality:
  rms_residual_mps2: 0.14528880815612949
  num_clusters: 19
  num_samples: 2197
noise_fit:
  stationary_samples: 1740
  method: bootstrap_rest
  phase: bootstrap